services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: Dockerfile-client
    networks:
      - express-networks
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: load-balancer
    depends_on:
      - express
    environment:
      - NGINX_SERVER_NAME=localhost
      - EXPRESS_HOST_1=project1-express-1
      # - EXPRESS_HOST_2=my-express-cadt-2-master-express-2
      # - EXPRESS_HOST_3=my-express-cadt-2-master-express-3
      - EXPRESS_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 3000:3000
    networks:
      - express-networks
  express:
    build:
      context: .
      dockerfile: Dockerfile-services
    volumes:
      - ./server/src:/app/src
      - ./server/index.js:/app/index.js
      - ./server/.env:/app/.env
      - ./server/uploads:/app/uploads
      - ./server/index.html:/app/index.html
    networks:
      - express-networks
    scale: 1
    depends_on:
      - mongodb
      - redis
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - express-networks
  redis:
    image: redis:5
    container_name: cadt-redis
    ports:
      - 6379:6379
    networks:
      - express-networks
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:cadt-redis:6379
    ports:
      - "8082:8081"
    networks:
      - express-networks
    depends_on:
      - redis
volumes:
  mongodbdata:
networks:
  production-networks:
    external: true