FROM node:18-slim
RUN npm install -g serve
WORKDIR /app

# Copy only the dependency files first
COPY ./client/package.json ./client/package-lock.json .env.client ./
COPY client .
RUN cp .env.client .env
RUN npm install

# Copy the application files excluding unnecessary items (.dockerignore handles this)
RUN npm run build

EXPOSE 4000

CMD ["serve","-l","4000", "dist"]

# Start the application
# CMD ["npm", "run", "dev"]
