name: Deploy to VM
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 62.146.177.21
          username: root
          key: ${{ secrets.SSH_CONTABO_KEY }}
          port: 22
          script: |
            . ~/.nvm/nvm.sh
            whoami
            pwd
            ls
            cd project-deploy
            git pull
            pm2 restart all
           # pm2 restart dev
